### ISSUE TITLE
Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by nbouvrette** [octokit/request.js#448]
Please update `node-fetch` to fix vulnerability issue:

```sh
node-fetch  <3.1.1
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
```

**Comment by wolfy1339** [comment]
We cannot upgrade to v3 of node-fetch since it is now an ESM module.

However, we can upgrade to 2.6.7 which contains a backported fix for that vulnerability.

But, the octokit modules are unmaintained.
For more information, check out [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), and subscribe for any further updates.

Considering that, I am considering maybe pushing a hotfix for this vulnerability

**Comment by jbrunton** [comment]
@wolfy1339: Thank you for clarifying, and thanks in advance for the hotfix.

Is there any official line on whether Octokit will be maintained in future or deprecated? It's still listed as the official API library in the [GitHub docs](https://docs.github.com/en/rest/overview/libraries) and I don't see any mention that it's deprecated in the readme.

**Comment by wolfy1339** [comment]
> Is there any official line on whether Octokit will be maintained in future or deprecated?

I'm only a volunteer community contributor. I don't have a line to GitHub.

Unfortunately, I don't have any further information.
