### ISSUE TITLE
[BUG]: Redirect option is not passed through...

### ISSUE THREAD

**Issue by mitchcapper** [octokit/request.js#635]
### What happened?

Seems to be:
#611

which in theory was fixed by #612 but #612 seems to be missing any code that actually passes the redirect through, only removes it as an option on the primary object.

What is interesting is this used to work (not sure if after #612 )  https://github.com/octokit/octokit.js/issues/1999 but I didn't bisect to figure out what changes stopped it from doing so.

While I could be missing something it looks like we manually build the fetch object, so I don't see how this option would be properly set other than with specifying it (see PR for this).

This specifically breaks the situation where you want to get the download URL for an artifact but not actually download it.

### Versions

Octokit/request 8.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
That issue that you linked is outdated. We stopped utilizing `node-fetch` in favour of the [Fetch API](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch) for better cross platform compatibility.

We removed the ability to pass through custom options in #599 and it was intentional that the `redirect` option was removed

Currently, you would need to do something like so:
```js
import { request } from "@octokit/request";
const customFetch = (url, options) => {
    return fetch(url, { redirect: "manual", ...options });
};
```

**Comment by mitchcapper** [comment]
Cheers.   After reading through the details of #599 I do see where it was removed, not 100% sure why but thank you for the workaround above.   I don't know if it makes sense to log a warning for some of the more common valid prior options that are now ignored.

**Comment by wolfy1339** [comment]
Reopening for awareness, and further discussions
